version: '3.4'

services:    
  qgrid.sqlserver.test:
    image: qgrid.test
    build:
        context: .
        dockerfile: Dockerfile
        target: test
        
  qgrid.postgres.test:
    image: qgrid.test
    build:
        context: .
        dockerfile: Dockerfile
        target: test
        
  qgrid.mysql.test:
    image: qgrid.test
    build:
        context: .
        dockerfile: Dockerfile
        target: test