version: '3.4'

services:
  qgrid.sqlserver.test:
    environment:
      - DBSERVER=MSSQL
      - CONNECTION_STRING=Server=sqlserver;Database=master;User=sa;Password=123QGridTest!@#;
    entrypoint: dotnet test -c Release --no-build --logger "trx;LogFileName=SqlServerTests.trx" --results-directory /var/temp/test-results QGrid.Tests.csproj
    volumes:
      - ../test-results:/var/temp/test-results
      
  qgrid.postgres.test:
    environment:
      - DBSERVER=POSTGRES
      - CONNECTION_STRING=Server=postgres;Port=5432;User Id=postgres;Password=123QGridTest!@#;Database=postgres;
    entrypoint: dotnet test -c Release --no-build --logger "trx;LogFileName=PostgreSQLTests.trx" --results-directory /var/temp/test-results QGrid.Tests.csproj
    volumes:
      - ../test-results:/var/temp/test-results
      
  qgrid.mysql.test:
    environment:
      - DBSERVER=MYSQL
      - CONNECTION_STRING=server=mysql;uid=root;pwd=123QGridTest!@#;database=qgrid;
    entrypoint: dotnet test -c Release --no-build --logger "trx;LogFileName=MySQLTests.trx" --results-directory /var/temp/test-results QGrid.Tests.csproj
    volumes:
      - ../test-results:/var/temp/test-results        