version: '3.4'

services:
  qgrid.test:
    environment:
      - DBSERVER=MSSQL
      - CONNECTION_STRING=Server=sqlserver;Database=qgrid;User=sa;Password=123QGridTest!@#;
    entrypoint: dotnet test -c Release --no-build --logger "trx;LogFileName=SqlServerTests.trx" --results-directory /var/temp/test-results QGrid.Tests.csproj
    volumes:
      - ../test-results:/var/temp/test-results
    depends_on:
      - sqlserver
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "123QGridTest!@#"
      ACCEPT_EULA: "Y"