version: '3.4'

services:      
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "123QGridTest!@#"
      ACCEPT_EULA: "Y"
      
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123QGridTest!@#
      - PGDATA=/pgdata
    restart: always
    
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123QGridTest!@#
      MYSQL_DATABASE: qgrid
    ports:
      - "3306:3306"