# This is a basic workflow to help you get started with Actions

name: Run Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup databases
        run: docker-compose -f src/docker-compose.db.yml up
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run tests
        run: docker-compose -f src/docker-compose.yml src/docker-compose.override.yml up
        
      - name: Cleanup
        run: docker-compose down --remove-orphans
